dao-program:
  - dao-programs/*
  - dao-programs/**/*

frontend:
  - any: ['apps/web/**/*']

tutorial:
  - any: ['tutorials/**/*']

docs:
  - any: ['apps/docs/**/*']

actions:
  - any: ['.github/actions/**/*']
